# Generated by Django 5.0.2 on 2024-02-27 01:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IMUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("first_name", models.CharField(blank=True, max_length=155)),
                ("last_name", models.CharField(blank=True, max_length=155)),
                ("middle_name", models.CharField(blank=True, max_length=155)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("EIT", "EIT"),
                            ("TEACHING_FELLOW", "TEACHING FELLOW"),
                            ("ADMIN_STAFF", "ADMINISTRATIVE STAFF"),
                            ("ADMIN", "ADMINSTRATOR"),
                        ],
                        default="EIT",
                        max_length=20,
                    ),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
            options={"abstract": False,},
        ),
    ]
