# Generated by Django 5.0.2 on 2024-02-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="imuser", name="is_active",),
        migrations.RemoveField(model_name="imuser", name="is_staff",),
    ]
